// portfolio/src/components/header.jsx
import { Link } from "react-router-dom"

export default function Header() {
    const menu = ['Profile', 'Works', 'Blog']
    return(
        <>
            <div className="bg-base-5 h-20 flex items-center justify-center">
                <div className="w-1/3 h-full">
                    <img src={"/profile.png"} alt="" className="rounded-full w-20 h-20 p-1" />
                </div>
                <div className="w-1/3">
                    <p className="text-center main-font text-xl">勝田紳太郎</p>
                </div>                
                <div className="w-1/3 flex justify-between">
                    {menu.map((item) => (
                        <Link to={`/${item.toLowerCase()}`} className="hidden iphone:block cursor-pointer">{item}</Link>                    
                    ))}
                </div>
            </div>
        </>
    )
}

// components/header.vue
<template>
  <header class="w-full bg-blue-800 p-2">
    <div class="grid grid-flow-col">
      <NuxtLink to="/"
        class="w-fit font-robotoSlab text-xl font-bold text-white border-2 border-white p-1 rounded-lg hover:bg-blue-600">
        {{ name }}
      </NuxtLink>
      <div class="flex items-center justify-center gap-6 xs:hidden md:inline-flex">
        <NuxtLink :to="'/' + link.toLowerCase()" v-for="link in links"
          class="w-fit font-shipporiAntique text-md font-light text-white hover:bg-blue-600 p-2 rounded-lg">
          {{ link }}
        </NuxtLink>
      </div>
      <UIcon name="mi-menu" class="w-8 h-8 justify-self-end hover:bg-blue-600 p-2 rounded-lg xs:block md:hidden" />
    </div>
  </header>
</template>

<script setup>
const name = ref("Shintaro");
const links = ref(["Profile", "Works", "Blog"]);
</script>
