// portfolio/src/components/blog.jsx
import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";

import Header from "./header"
import Menu from "./menu";
import axios from "axios";
import dayjs from 'dayjs'

export default function Blog() {
    const [articles, setArticles] = useState([])

    const icons = ["/likes_count.svg", "/stocks_count.svg", "/comments_count.svg", "/page_views_count.svg"];
    
    const getArticlesFromQiita = async () => {
        try{
            const response =  await axios.get("https://qiita.com/api/v2/users/sintaro-katuta/items",
                {
                    headers: {
                        Authorization: `Bearer ${process.env.REACT_APP_QIITA_ACCESS_TOKEN}`,
                    },
                }
            )
            return response.data
        }catch(e){
            console.log(e)
        }
    }

    useEffect(() => {
        getArticlesFromQiita().then(setArticles)
    }, [])

    return(
        <div className="w-full h-full flex flex-col gap-10 justify-start items-center overflow-y-auto px-3 py-5">
            {articles.map((article, i) => (
                <div key={i} className="flex-none border-2 border-qiita w-full h-1/5 rounded-xl p-3 shadow-xl flex flex-col justify-center gap-10">
                    <Link className="w-fit" to={article.url}>
                        <p className="text-lg font-semibold underline decoration-solid cursor-pointer tracking-wide">{article.title}</p>
                    </Link>                            
                    <div className="w-full flex items-center justify-start gap-3">
                        <div className="flex justify-center items-center">
                            <img src="/likes_count.svg" alt="" className="w-5 h-full" />
                            <p className="text-sm">{article.likes_count}</p>
                        </div>
                        <div className="flex justify-center items-center">
                            <img src="/stocks_count.svg" alt="" className="w-5 h-full" />
                            <p className="text-sm">{article.stocks_count}</p>
                        </div>
                        <div className="flex justify-center items-center">
                            <img src="/comments_count.svg" alt="" className="w-5 h-full" />
                            <p className="text-sm">{article.comments_count}</p>
                        </div>
                        {/* <p>{item.tags}</p> */}
                        <p className="text-sm">{dayjs(article.created_at).format('YYYY年MM月DD日 HH:MM')}</p>
                    </div>
                </div>
            ))}
            <Link to="/blog/edit">
                <img src="/upload_file.svg" alt="" className="absolute w-20 h-20 cursor-pointer bottom-20 right-10" />
            </Link>
        </div>
    )
}

// pages/blog.vue
<template>
  <Header />
  <p id="title" class="font-appleSystem font-medium text-3xl text-center p-4">🌟 Blog 📗</p>
  <UContainer class="w-full h-full grid md:grid-cols-2 max-md:grid-cols-1 gap-4 py-8">
    <UCard hover v-for="article in articles" :key="article.id" class="article w-full h-full">
      <template #header>
        <div class="flex items-center gap-4 py-2">
          <img :src="article.user.profile_image_url" alt="" class="w-8 h-8 rounded-full" />
          <p class="text-sm text-gray-500">{{ article.user.id }}({{ article.user.name }})</p>
        </div>
        <div class="flex justify-between items-center">
          <ULink as="button" :to="article.url" class="title text-xl text-white truncate">{{ article.title }}</ULink>
        </div>
      </template>
      <p class="truncate">{{ article.description }}</p>
        <div class="flex gap-2 mb-4">
          <p v-for="tag in article.tags" class="h-fit text-sm border bg-gray-600 rounded-xl p-1">{{ tag.name }}</p>
        </div>
        <div class="flex items-center justify-start gap-4">
          <div class="flex items-center gap-1">
            <UIcon name="i-mi:heart" class="w-4 h-4" />
            <p class="like text-sm text-gray-500">{{ article.likes_count }}</p>
          </div>
          <p class="text-sm text-gray-500">作成日: {{ new Date(article.created_at).toLocaleDateString() }}</p>
        </div>
    </UCard>
  </UContainer>
</template>

<script setup>
const config = useRuntimeConfig();
const { data: articles, error } = await useFetch(
	"https://qiita.com/api/v2/users/sintaro-katuta/items",
	{
		headers: {
			Authorization: `Bearer ${config.public.QIITA_ACCESS_TOKEN}`,
		},
	},
);

if (error.value) {
	console.error(error.value);
}

console.log(articles.value);
</script>
